timeout: 1200s
steps:

  - id: pull
    name: gcr.io/cloud-builders/docker
    args: [pull, "gcr.io/${PROJECT_ID}/jenkins-master:${COMMIT_SHA}"]

  - id: tag-name
    name: gcr.io/cloud-builders/docker
    args: [tag, "gcr.io/${PROJECT_ID}/jenkins-master:${COMMIT_SHA}", "gcr.io/${PROJECT_ID}/jenkins-master:${TAG_NAME}"]
    waitFor: [pull]

  - id: tag-latest
    name: gcr.io/cloud-builders/docker
    args: [tag, "gcr.io/${PROJECT_ID}/jenkins-master:${COMMIT_SHA}", "gcr.io/${PROJECT_ID}/jenkins-master:latest"]
    waitFor: [tag-name]

images: ["gcr.io/${PROJECT_ID}/jenkins-master:${TAG_NAME}", "gcr.io/${PROJECT_ID}/jenkins-master:latest"]
